// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: products/protocol/service.proto

package protocol

import (
	common "github.com/vniche/distributed-tracing/common"
	protocol "github.com/vniche/distributed-tracing/orders/protocol"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetProductOrdersRequest represents a request payload for GetProductOrders method
type GetProductOrdersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// product id of orders to be queried
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetProductOrdersRequest) Reset() {
	*x = GetProductOrdersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_products_protocol_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetProductOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductOrdersRequest) ProtoMessage() {}

func (x *GetProductOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_products_protocol_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductOrdersRequest.ProtoReflect.Descriptor instead.
func (*GetProductOrdersRequest) Descriptor() ([]byte, []int) {
	return file_products_protocol_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetProductOrdersRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// GetProductOrdersResponse represents a response payload for GetProductOrders method
type GetProductOrdersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// product unique identifier
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// human-friendly product identifier
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// list of fetched product orders
	Orders []*protocol.Order `protobuf:"bytes,3,rep,name=orders,proto3" json:"orders,omitempty"`
}

func (x *GetProductOrdersResponse) Reset() {
	*x = GetProductOrdersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_products_protocol_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetProductOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductOrdersResponse) ProtoMessage() {}

func (x *GetProductOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_products_protocol_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductOrdersResponse.ProtoReflect.Descriptor instead.
func (*GetProductOrdersResponse) Descriptor() ([]byte, []int) {
	return file_products_protocol_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetProductOrdersResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetProductOrdersResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetProductOrdersResponse) GetOrders() []*protocol.Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

// Product data structure
type Product struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// resource unique identifier
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// human-friendly resource identifier
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Product) Reset() {
	*x = Product{}
	if protoimpl.UnsafeEnabled {
		mi := &file_products_protocol_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_products_protocol_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_products_protocol_service_proto_rawDescGZIP(), []int{2}
}

func (x *Product) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_products_protocol_service_proto protoreflect.FileDescriptor

var file_products_protocol_service_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0f, 0x6d, 0x65, 0x2e, 0x76, 0x6e, 0x69, 0x63, 0x68, 0x65, 0x2e, 0x73, 0x74, 0x6f,
	0x72, 0x65, 0x1a, 0x13, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1d, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x29, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x6e, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x2e, 0x0a, 0x06, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x6d, 0x65, 0x2e, 0x76, 0x6e, 0x69, 0x63, 0x68, 0x65, 0x2e, 0x73, 0x74,
	0x6f, 0x72, 0x65, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x06, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x73, 0x22, 0x2d, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x32, 0xc3, 0x01, 0x0a, 0x08, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x12, 0x4c, 0x0a,
	0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x12, 0x18,
	0x2e, 0x6d, 0x65, 0x2e, 0x76, 0x6e, 0x69, 0x63, 0x68, 0x65, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x65,
	0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x1a, 0x1f, 0x2e, 0x6d, 0x65, 0x2e, 0x76, 0x6e,
	0x69, 0x63, 0x68, 0x65, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x69, 0x0a, 0x10, 0x47,
	0x65, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x12,
	0x28, 0x2e, 0x6d, 0x65, 0x2e, 0x76, 0x6e, 0x69, 0x63, 0x68, 0x65, 0x2e, 0x73, 0x74, 0x6f, 0x72,
	0x65, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x6d, 0x65, 0x2e, 0x76,
	0x6e, 0x69, 0x63, 0x68, 0x65, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x50,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x42, 0x5a, 0x40, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x76, 0x6e, 0x69, 0x63, 0x68, 0x65, 0x2f, 0x64, 0x69, 0x73, 0x74,
	0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x64, 0x2d, 0x74, 0x72, 0x61, 0x63, 0x69, 0x6e, 0x67, 0x2f,
	0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_products_protocol_service_proto_rawDescOnce sync.Once
	file_products_protocol_service_proto_rawDescData = file_products_protocol_service_proto_rawDesc
)

func file_products_protocol_service_proto_rawDescGZIP() []byte {
	file_products_protocol_service_proto_rawDescOnce.Do(func() {
		file_products_protocol_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_products_protocol_service_proto_rawDescData)
	})
	return file_products_protocol_service_proto_rawDescData
}

var file_products_protocol_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_products_protocol_service_proto_goTypes = []interface{}{
	(*GetProductOrdersRequest)(nil),  // 0: me.vniche.store.GetProductOrdersRequest
	(*GetProductOrdersResponse)(nil), // 1: me.vniche.store.GetProductOrdersResponse
	(*Product)(nil),                  // 2: me.vniche.store.Product
	(*protocol.Order)(nil),           // 3: me.vniche.store.Order
	(*common.ChangeResponse)(nil),    // 4: me.vniche.store.ChangeResponse
}
var file_products_protocol_service_proto_depIdxs = []int32{
	3, // 0: me.vniche.store.GetProductOrdersResponse.orders:type_name -> me.vniche.store.Order
	2, // 1: me.vniche.store.Products.CreateProduct:input_type -> me.vniche.store.Product
	0, // 2: me.vniche.store.Products.GetProductOrders:input_type -> me.vniche.store.GetProductOrdersRequest
	4, // 3: me.vniche.store.Products.CreateProduct:output_type -> me.vniche.store.ChangeResponse
	1, // 4: me.vniche.store.Products.GetProductOrders:output_type -> me.vniche.store.GetProductOrdersResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_products_protocol_service_proto_init() }
func file_products_protocol_service_proto_init() {
	if File_products_protocol_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_products_protocol_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetProductOrdersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_products_protocol_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetProductOrdersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_products_protocol_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Product); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_products_protocol_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_products_protocol_service_proto_goTypes,
		DependencyIndexes: file_products_protocol_service_proto_depIdxs,
		MessageInfos:      file_products_protocol_service_proto_msgTypes,
	}.Build()
	File_products_protocol_service_proto = out.File
	file_products_protocol_service_proto_rawDesc = nil
	file_products_protocol_service_proto_goTypes = nil
	file_products_protocol_service_proto_depIdxs = nil
}
